// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class AMTQuestion
{
    public int AMTQuestionId { get; set; }

    public string Question { get; set; }

    public int? Ordering { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedBy_FK { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy_FK { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<PatientAMTAnswer> PatientAMTAnswers { get; set; } = new List<PatientAMTAnswer>();
}