// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class APIOrderMedication
{
    public int APIOrderMedicationID { get; set; }

    public int APIOrderID_FK { get; set; }

    public int? MedicationID { get; set; }

    public string MedicationName { get; set; }

    public string MedicationStatus { get; set; }

    public int? MedicationQuantity { get; set; }

    public string MedicationQuantityUnit { get; set; }

    public int? MedicationFrequencyID { get; set; }

    public int? MedicationFrequency { get; set; }

    public int? MedicationPeriod { get; set; }

    public string MedicationPeriodUnit { get; set; }

    public bool? MedicationAsNeeded { get; set; }

    public string MedicationDisplay { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedBy_FK { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy_FK { get; set; }

    public bool IsDeleted { get; set; }

    public int? DosageID_FK { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public virtual APIOrder APIOrderID_FKNavigation { get; set; }
}