// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class Audit_Type
{
    public string AuditAction { get; set; }

    public DateTime ActionTime { get; set; }

    public string code { get; set; }

    public string codeValue { get; set; }

    public string parentCode { get; set; }

    public int ordering { get; set; }

    public DateTime created { get; set; }

    public DateTime? updated { get; set; }
}