// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class Audit_VitalSignDetail
{
    public string AuditAction { get; set; }

    public DateTime ActionTime { get; set; }

    public int id { get; set; }

    public int vitalSignTypeId { get; set; }

    public int vitalSignId { get; set; }

    public decimal detailValue { get; set; }

    public bool IsDeleted { get; set; }
}