// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class Audit_APIMonitor
{
    public string AuditAction { get; set; }

    public DateTime ActionTime { get; set; }

    public int? MonitorID { get; set; }

    public string UUID { get; set; }

    public string APIName { get; set; }

    public DateTime CreatedDate { get; set; }
}