// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class AuditTrail
{
    public int AuditTrailId { get; set; }

    public string AuditAction { get; set; }

    public string Module { get; set; }

    public string Event { get; set; }

    public string IPAddress { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? CreatedBy_FK { get; set; }

    public string APIRequest { get; set; }

    public virtual User CreatedBy_FKNavigation { get; set; }
}