// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class Audit_CarePlanSub
{
    public string AuditAction { get; set; }

    public DateTime ActionTime { get; set; }

    public int CarePlanSubID { get; set; }

    public int CarePlanID_FK { get; set; }

    public int SubCarePlanName { get; set; }

    public string Goal { get; set; }

    public DateTime? ReviewDate { get; set; }

    public int? PersonInCharge { get; set; }

    public DateTime? ApprovedDate { get; set; }

    public bool? IsDeleted { get; set; }

    public int? GroupCode { get; set; }

    public string CarePlanGroupName { get; set; }

    public int? DiseaseID_FK { get; set; }

    public string InterventionStatus { get; set; }

    public string GoalStatus { get; set; }
}