// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class Audit_GroupRole
{
    public string AuditAction { get; set; }

    public DateTime ActionTime { get; set; }

    public int GroupId_FK { get; set; }

    public int RoleId_FK { get; set; }

    public string Role { get; set; }
}