// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class Audit_InitialCareAssessmentVitalSign
{
    public string AuditAction { get; set; }

    public DateTime ActionTime { get; set; }

    public int InitialCareAssessmentID_FK { get; set; }

    public int VitalSignID_FK { get; set; }

    public DateTime? TimeOfRecord { get; set; }
}