// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class BillingProposal
{
    public int BillingProposalID { get; set; }

    public int PatientID_FK { get; set; }

    public string ProposalNumber { get; set; }

    public string Title { get; set; }

    public bool? SendEmail { get; set; }

    public bool? EmailPatient { get; set; }

    public string EmailTo { get; set; }

    public string EmailCC { get; set; }

    public string EmailBCC { get; set; }

    public int CurrencyID_FK { get; set; }

    public decimal TotalCost { get; set; }

    public string Status { get; set; }

    public string GroupNumber { get; set; }

    public short Version { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy_FK { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy_FK { get; set; }

    public bool IsDeleted { get; set; }

    public string ProposalType { get; set; }

    public virtual ICollection<BillingInvoiceService> BillingInvoiceServices { get; set; } = new List<BillingInvoiceService>();

    public virtual ICollection<BillingProposalService> BillingProposalServices { get; set; } = new List<BillingProposalService>();

    public virtual User CreatedBy_FKNavigation { get; set; }

    public virtual Code CurrencyID_FKNavigation { get; set; }

    public virtual User ModifiedBy_FKNavigation { get; set; }

    public virtual Patient PatientID_FKNavigation { get; set; }
}