// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class CarePlanDetail
{
    public int CarePlanDetailID { get; set; }

    public int CarePlanSubID_FK { get; set; }

    public int SystemID_FK { get; set; }

    public int DiseaseID_FK { get; set; }

    public int? DiseaseSubInfoID_FK { get; set; }

    public virtual CarePlanSub CarePlanSubID_FKNavigation { get; set; }

    public virtual Disease DiseaseID_FKNavigation { get; set; }

    public virtual SystemForDisease SystemID_FKNavigation { get; set; }
}