// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class CarePlanSub
{
    public int CarePlanSubID { get; set; }

    public int CarePlanID_FK { get; set; }

    public int SubCarePlanName { get; set; }

    public string Goal { get; set; }

    public DateTime? ReviewDate { get; set; }

    public int? PersonInCharge { get; set; }

    public DateTime? ApprovedDate { get; set; }

    public bool? IsDeleted { get; set; }

    public int? GroupCode { get; set; }

    public string CarePlanGroupName { get; set; }

    public int? DiseaseID_FK { get; set; }

    public string InterventionStatus { get; set; }

    public string GoalStatus { get; set; }

    public virtual ICollection<CarePlanDetail> CarePlanDetails { get; set; } = new List<CarePlanDetail>();

    public virtual CarePlan CarePlanID_FKNavigation { get; set; }

    public virtual ICollection<CarePlanSubGoal> CarePlanSubGoals { get; set; } = new List<CarePlanSubGoal>();

    public virtual ICollection<CarePlanSubProblemList> CarePlanSubProblemLists { get; set; } = new List<CarePlanSubProblemList>();

    public virtual ICollection<Activity> ActivityID_FKs { get; set; } = new List<Activity>();

    public virtual ICollection<CPGoal> CPGoalsID_FKs { get; set; } = new List<CPGoal>();

    public virtual ICollection<Intervention> InterventionID_FKs { get; set; } = new List<Intervention>();
}