// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class CarePlanStatus
{
    public int CarePlanStatusID { get; set; }

    public string CarePlanStatus1 { get; set; }

    public string CareReviewFrequency { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedBy_FK { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy_FK { get; set; }

    public virtual ICollection<CarePlan> CarePlans { get; set; } = new List<CarePlan>();
}