// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class CareReportSocialSupport
{
    public int CareReportSocialSupportID { get; set; }

    public int CareReportID_FK { get; set; }

    public int PatientSocialSupportID_FK { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedBy_FK { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy_FK { get; set; }

    public virtual CareReport CareReportID_FKNavigation { get; set; }

    public virtual PatientSocialSupport PatientSocialSupportID_FKNavigation { get; set; }
}