// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class Code
{
    public int CodeId { get; set; }

    public int CodeTypeId_FK { get; set; }

    public string CodeName { get; set; }

    public int? Ordering { get; set; }

    public bool IsSystemUsed { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedBy_FK { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy_FK { get; set; }

    public bool? Indication_Acute { get; set; }

    public bool? Indication_PRN { get; set; }

    public string Referral_Code { get; set; }

    public bool? AllergyReaction_Drug { get; set; }

    public bool? AllergyReaction_Others { get; set; }

    public int? MedicationGroupID_FK { get; set; }

    public string Status { get; set; }

    public string CurrencyCodeA { get; set; }

    public string CurrencyCodeN { get; set; }

    public string CurrencyInvoiceFooter { get; set; }

    public bool? Critical { get; set; }

    public virtual ICollection<BillingInvoice> BillingInvoices { get; set; } = new List<BillingInvoice>();

    public virtual ICollection<BillingProposal> BillingProposals { get; set; } = new List<BillingProposal>();

    public virtual ICollection<BillingService> BillingServices { get; set; } = new List<BillingService>();

    public virtual ICollection<Branch> Branches { get; set; } = new List<Branch>();

    public virtual ICollection<CarePlanSubProblemListGoal> CarePlanSubProblemListGoalOperators { get; set; } = new List<CarePlanSubProblemListGoal>();

    public virtual ICollection<CarePlanSubProblemListGoal> CarePlanSubProblemListGoalScoreTypes { get; set; } = new List<CarePlanSubProblemListGoal>();

    public virtual ICollection<CareReport> CareReportAirwayBreathingID_FKNavigations { get; set; } = new List<CareReport>();

    public virtual ICollection<CareReport> CareReportBladderCareID_FKNavigations { get; set; } = new List<CareReport>();

    public virtual ICollection<CareReport> CareReportBowelCareID_FKNavigations { get; set; } = new List<CareReport>();

    public virtual ICollection<CareReport> CareReportCapillaryRefillID_FKNavigations { get; set; } = new List<CareReport>();

    public virtual ICollection<CareReport> CareReportCirculationID_FKNavigations { get; set; } = new List<CareReport>();

    public virtual ICollection<CareReport> CareReportCoughID_FKNavigations { get; set; } = new List<CareReport>();

    public virtual ICollection<CareReport> CareReportDiapersID_FKNavigations { get; set; } = new List<CareReport>();

    public virtual ICollection<CareReport> CareReportLipsID_FKNavigations { get; set; } = new List<CareReport>();

    public virtual ICollection<CareReport> CareReportLowerEyelidsID_FKNavigations { get; set; } = new List<CareReport>();

    public virtual ICollection<CareReport> CareReportO2AidID_FKNavigations { get; set; } = new List<CareReport>();

    public virtual ICollection<CareReport> CareReportPainDescriptionID_FKNavigations { get; set; } = new List<CareReport>();

    public virtual ICollection<CareReport> CareReportPeripheralPulsesPedalID_FKNavigations { get; set; } = new List<CareReport>();

    public virtual ICollection<CareReport> CareReportPeripheralPulsesRadialID_FKNavigations { get; set; } = new List<CareReport>();

    public virtual ICollection<CareReport> CareReportSleepRestID_FKNavigations { get; set; } = new List<CareReport>();

    public virtual ICollection<CareReport> CareReportTemperatureID_FKNavigations { get; set; } = new List<CareReport>();

    public virtual CodeType CodeTypeId_FKNavigation { get; set; }

    public virtual ICollection<Enquiry> EnquiryCaregiverAtHomeID_FKNavigations { get; set; } = new List<Enquiry>();

    public virtual ICollection<Enquiry> EnquiryEnquirySourceID_FKNavigations { get; set; } = new List<Enquiry>();

    public virtual ICollection<Enquiry> EnquiryGenderID_FKNavigations { get; set; } = new List<Enquiry>();

    public virtual ICollection<Enquiry> EnquiryPreferredLanguageID_FKNavigations { get; set; } = new List<Enquiry>();

    public virtual ICollection<Enquiry> EnquiryRaceID_FKNavigations { get; set; } = new List<Enquiry>();

    public virtual ICollection<Enquiry> EnquiryServicesRequiredID_FKNavigations { get; set; } = new List<Enquiry>();

    public virtual ICollection<Enquiry> EnquiryUserOrganizationID_FKNavigations { get; set; } = new List<Enquiry>();

    public virtual ICollection<Event> EventEventTypeID_FKNavigations { get; set; } = new List<Event>();

    public virtual ICollection<Event> EventPeriodTypeID_FKNavigations { get; set; } = new List<Event>();

    public virtual ICollection<Facility> Facilities { get; set; } = new List<Facility>();

    public virtual ICollection<Code> InverseMedicationGroupID_FKNavigation { get; set; } = new List<Code>();

    public virtual ICollection<Item> ItemCategoryID_FKNavigations { get; set; } = new List<Item>();

    public virtual ICollection<Item> ItemItemUnitID_FKNavigations { get; set; } = new List<Item>();

    public virtual Code MedicationGroupID_FKNavigation { get; set; }

    public virtual ICollection<MedicationVitalSignType> MedicationVitalSignTypes { get; set; } = new List<MedicationVitalSignType>();

    public virtual ICollection<NutritionTaskReference> NutritionTaskReferences { get; set; } = new List<NutritionTaskReference>();

    public virtual ICollection<NutritionTask> NutritionTasks { get; set; } = new List<NutritionTask>();

    public virtual ICollection<Patient> PatientBloodTypeID_FKNavigations { get; set; } = new List<Patient>();

    public virtual ICollection<PatientDrugAllergy> PatientDrugAllergyMedicationID_FKNavigations { get; set; } = new List<PatientDrugAllergy>();

    public virtual ICollection<PatientDrugAllergy> PatientDrugAllergyReactionID_FKNavigations { get; set; } = new List<PatientDrugAllergy>();

    public virtual ICollection<Patient> PatientGenderID_FKNavigations { get; set; } = new List<Patient>();

    public virtual ICollection<Patient> PatientInvoiceModeID_FKNavigations { get; set; } = new List<Patient>();

    public virtual ICollection<Patient> PatientMaritalStatusID_FKNavigations { get; set; } = new List<Patient>();

    public virtual ICollection<PatientMedicalHistory> PatientMedicalHistories { get; set; } = new List<PatientMedicalHistory>();

    public virtual ICollection<PatientMedicationConsume> PatientMedicationConsumeAcutePRNIndicationID_FKNavigations { get; set; } = new List<PatientMedicationConsume>();

    public virtual ICollection<PatientMedicationConsume> PatientMedicationConsumeDosageID_FKNavigations { get; set; } = new List<PatientMedicationConsume>();

    public virtual ICollection<PatientMedicationConsume> PatientMedicationConsumeFrequencyID_FKNavigations { get; set; } = new List<PatientMedicationConsume>();

    public virtual ICollection<PatientMedicationConsume> PatientMedicationConsumeInstructedBy2ID_FKNavigations { get; set; } = new List<PatientMedicationConsume>();

    public virtual ICollection<PatientMedicationConsume> PatientMedicationConsumeInstructedByID_FKNavigations { get; set; } = new List<PatientMedicationConsume>();

    public virtual ICollection<PatientMedicationConsume> PatientMedicationConsumeMedicationID_FKNavigations { get; set; } = new List<PatientMedicationConsume>();

    public virtual ICollection<PatientMedicationConsume> PatientMedicationConsumeRouteID_FKNavigations { get; set; } = new List<PatientMedicationConsume>();

    public virtual ICollection<PatientOtherAllergy> PatientOtherAllergyDescriptionID_FKNavigations { get; set; } = new List<PatientOtherAllergy>();

    public virtual ICollection<PatientOtherAllergy> PatientOtherAllergyReactionID_FKNavigations { get; set; } = new List<PatientOtherAllergy>();

    public virtual ICollection<Patient> PatientPatientReferralByID_FKNavigations { get; set; } = new List<Patient>();

    public virtual ICollection<Patient> PatientPatientTypeID_FKNavigations { get; set; } = new List<Patient>();

    public virtual ICollection<PatientProfile> PatientProfileBloodTypeID_FKNavigations { get; set; } = new List<PatientProfile>();

    public virtual ICollection<PatientProfile> PatientProfilePatientOrganizationID_FKNavigations { get; set; } = new List<PatientProfile>();

    public virtual ICollection<PatientProfile> PatientProfileReligionID_FKNavigations { get; set; } = new List<PatientProfile>();

    public virtual ICollection<Patient> PatientRaceID_FKNavigations { get; set; } = new List<Patient>();

    public virtual ICollection<Patient> PatientReligionID_FKNavigations { get; set; } = new List<Patient>();

    public virtual ICollection<Patient> PatientResidentTypeID_FKNavigations { get; set; } = new List<Patient>();

    public virtual ICollection<PatientSocialSupport> PatientSocialSupportGenderID_FKNavigations { get; set; } = new List<PatientSocialSupport>();

    public virtual ICollection<PatientSocialSupport> PatientSocialSupportMaritalStatusID_FKNavigations { get; set; } = new List<PatientSocialSupport>();

    public virtual ICollection<PatientSocialSupport> PatientSocialSupportNationalityID_FKNavigations { get; set; } = new List<PatientSocialSupport>();

    public virtual ICollection<PatientSocialSupport> PatientSocialSupportRelationshipID_FKNavigations { get; set; } = new List<PatientSocialSupport>();

    public virtual ICollection<PatientWoundDraft> PatientWoundDrafts { get; set; } = new List<PatientWoundDraft>();

    public virtual ICollection<PatientWound> PatientWounds { get; set; } = new List<PatientWound>();

    public virtual ICollection<ProblemListGoal> ProblemListGoalOperators { get; set; } = new List<ProblemListGoal>();

    public virtual ICollection<ProblemListGoal> ProblemListGoalScoreTypes { get; set; } = new List<ProblemListGoal>();

    public virtual ICollection<Receipt> ReceiptCurrencyID_FKNavigations { get; set; } = new List<Receipt>();

    public virtual ICollection<Receipt> ReceiptPaymentModeID_FKNavigations { get; set; } = new List<Receipt>();

    public virtual ICollection<Resource> Resources { get; set; } = new List<Resource>();

    public virtual ICollection<ServiceForBillingCost> ServiceForBillingCosts { get; set; } = new List<ServiceForBillingCost>();

    public virtual ICollection<ServiceForBilling> ServiceForBillings { get; set; } = new List<ServiceForBilling>();

    public virtual ICollection<TD_WoundAssessmentFactor> TD_WoundAssessmentFactors { get; set; } = new List<TD_WoundAssessmentFactor>();

    public virtual ICollection<Task> TaskActionTypeID_FKNavigations { get; set; } = new List<Task>();

    public virtual ICollection<Task> TaskDosageID_FKNavigations { get; set; } = new List<Task>();

    public virtual ICollection<Task> TaskFrequencyID_FKNavigations { get; set; } = new List<Task>();

    public virtual ICollection<Task> TaskMedicationID_FKNavigations { get; set; } = new List<Task>();

    public virtual ICollection<TeleconsultationRecording> TeleconsultationRecordings { get; set; } = new List<TeleconsultationRecording>();

    public virtual ICollection<TreatmentListItem> TreatmentListItems { get; set; } = new List<TreatmentListItem>();

    public virtual ICollection<UserCategory> UserCategories { get; set; } = new List<UserCategory>();

    public virtual ICollection<Enquiry> EnquiryID_FKs { get; set; } = new List<Enquiry>();

    public virtual ICollection<Enquiry> EnquiryID_FKsNavigation { get; set; } = new List<Enquiry>();

    public virtual ICollection<InitialCareAssessment> InitialCareAssessmentID_FKs { get; set; } = new List<InitialCareAssessment>();

    public virtual ICollection<Patient> PatientID_FKs { get; set; } = new List<Patient>();

    public virtual ICollection<Patient> PatientID_FKsNavigation { get; set; } = new List<Patient>();

    public virtual ICollection<PatientMedication> PatientMedicationID_FKs { get; set; } = new List<PatientMedication>();

    public virtual ICollection<PatientReferral> PatientReferralID_FKs { get; set; } = new List<PatientReferral>();

    public virtual ICollection<PatientWoundDraft> PatientWoundDraftID_FKs { get; set; } = new List<PatientWoundDraft>();

    public virtual ICollection<PatientWoundVisit> PatientWoundVisitID_FKs { get; set; } = new List<PatientWoundVisit>();

    public virtual ICollection<PatientWoundVisit> PatientWoundVisitID_FKs1 { get; set; } = new List<PatientWoundVisit>();

    public virtual ICollection<PatientWoundVisit> PatientWoundVisitID_FKsNavigation { get; set; } = new List<PatientWoundVisit>();

    public virtual ICollection<Code> ServiceID_FKs { get; set; } = new List<Code>();

    public virtual ICollection<Code> SkillsetID_FKs { get; set; } = new List<Code>();

    public virtual ICollection<Task> TaskID_FKs { get; set; } = new List<Task>();

    public virtual ICollection<User> UserID_FKs { get; set; } = new List<User>();

    public virtual ICollection<User> UserID_FKsNavigation { get; set; } = new List<User>();

    public virtual ICollection<User> UserId_FKs { get; set; } = new List<User>();
}