// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class DischargeSummaryReport
{
    public int DischargeSummaryReportId { get; set; }

    public int PatientID_FK { get; set; }

    public string Status { get; set; }

    public DateTime? DischargeDate { get; set; }

    public DateTime? VisitDateStart { get; set; }

    public DateTime? VisitDateEnd { get; set; }

    public int? VisitedBy_FK { get; set; }

    public string SummaryCaseNote { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedBy_FK { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy_FK { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<DischargeSummaryReportAttachment> DischargeSummaryReportAttachments { get; set; } = new List<DischargeSummaryReportAttachment>();
}