// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class Disease
{
    public int DiseaseID { get; set; }

    public string DiseaseName { get; set; }

    public int SystemID_FK { get; set; }

    public bool IsAdditionalInfo { get; set; }

    public bool IsSuggestPalliativeCare { get; set; }

    public bool IsSystemUsed { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedBy_FK { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy_FK { get; set; }

    public string AdditionalInfo { get; set; }

    public string DiseaseCode { get; set; }

    public virtual ICollection<Activity> Activities { get; set; } = new List<Activity>();

    public virtual ICollection<CPGoal> CPGoals { get; set; } = new List<CPGoal>();

    public virtual ICollection<CarePlanDetail> CarePlanDetails { get; set; } = new List<CarePlanDetail>();

    public virtual ICollection<CarePlanSubGoal> CarePlanSubGoals { get; set; } = new List<CarePlanSubGoal>();

    public virtual ICollection<DiseaseInfo> DiseaseInfos { get; set; } = new List<DiseaseInfo>();

    public virtual ICollection<DiseaseSubInfo> DiseaseSubInfos { get; set; } = new List<DiseaseSubInfo>();

    public virtual ICollection<DiseaseVitalSignType> DiseaseVitalSignTypes { get; set; } = new List<DiseaseVitalSignType>();

    public virtual ICollection<Intervention> Interventions { get; set; } = new List<Intervention>();

    public virtual ICollection<PatientClinician> PatientClinicians { get; set; } = new List<PatientClinician>();

    public virtual ICollection<PatientFamilyHistory> PatientFamilyHistories { get; set; } = new List<PatientFamilyHistory>();

    public virtual ICollection<PatientMedicationConsume> PatientMedicationConsumes { get; set; } = new List<PatientMedicationConsume>();

    public virtual ICollection<ProblemList> ProblemLists { get; set; } = new List<ProblemList>();

    public virtual SystemForDisease SystemID_FKNavigation { get; set; }
}