// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class EnquiryConfig
{
    public int EnquiryConfigID { get; set; }

    public int? SCMID_FK { get; set; }

    public string EmailContent { get; set; }

    public int? EscalatingPersonID_FK { get; set; }

    public decimal? EscalationPeriod { get; set; }

    public string EscalationEmail { get; set; }

    public string EmailtoCMContent { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedBy_FK { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy_FK { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual User EscalatingPersonID_FKNavigation { get; set; }

    public virtual User SCMID_FKNavigation { get; set; }

    public virtual ICollection<User> UserID_FKs { get; set; } = new List<User>();

    public virtual ICollection<User> UserID_FKsNavigation { get; set; } = new List<User>();
}