// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class ErrorLog
{
    public int ErrorLogId { get; set; }

    public string ErrorDetails { get; set; }

    public DateTime DateCreated { get; set; }
}