// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class Facility
{
    public int FacilityID { get; set; }

    public string FacilityName { get; set; }

    public int OrganizationID_FK { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy_FK { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy_FK { get; set; }

    public string _id { get; set; }

    public string IntegrationSource { get; set; }

    public string Remarks { get; set; }

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual Code OrganizationID_FKNavigation { get; set; }

    public virtual ICollection<Patient> PatientID_FKs { get; set; } = new List<Patient>();

    public virtual ICollection<UserCategory> UserCategoryID_FKs { get; set; } = new List<UserCategory>();
}