// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class Item
{
    public int ItemID { get; set; }

    public string ItemName { get; set; }

    public int CategoryID_FK { get; set; }

    public int ItemUnitID_FK { get; set; }

    public int Quantity { get; set; }

    public decimal UnitPrice { get; set; }

    public bool? AvailableInBilling { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy_FK { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy_FK { get; set; }

    public virtual ICollection<BillingInvoiceConsumable> BillingInvoiceConsumables { get; set; } = new List<BillingInvoiceConsumable>();

    public virtual Code CategoryID_FKNavigation { get; set; }

    public virtual ICollection<ItemStock> ItemStocks { get; set; } = new List<ItemStock>();

    public virtual Code ItemUnitID_FKNavigation { get; set; }

    public virtual ICollection<PatientWoundVisitTreatment> PatientWoundVisitTreatments { get; set; } = new List<PatientWoundVisitTreatment>();
}