// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class Language
{
    public int LanguageId { get; set; }

    public string Name { get; set; }

    public string FullName { get; set; }

    public virtual ICollection<Resource> Resources { get; set; } = new List<Resource>();
}