// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class LoginDevice
{
    public int LoginDeviceId { get; set; }

    public int UserId_FK { get; set; }

    public string DeviceType { get; set; }

    public string DeviceID { get; set; }

    public DateTime CreatedDate { get; set; }
}