// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class MobileAppVersioning
{
    public int MobileVersionId { get; set; }

    public string AppName { get; set; }

    public string DeviceType { get; set; }

    public string Version { get; set; }

    public string Status { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedBy_FK { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy_FK { get; set; }

    public virtual User CreatedBy_FKNavigation { get; set; }

    public virtual User ModifiedBy_FKNavigation { get; set; }
}