// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class Notification
{
    public int id { get; set; }

    public int userId { get; set; }

    public string notificationTypeCode { get; set; }

    public bool isRead { get; set; }

    public bool isDeleted { get; set; }

    public DateTime createdDate { get; set; }

    public DateTime? updatedDate { get; set; }

    public int? FacilityID_FK { get; set; }

    public virtual Facility FacilityID_FKNavigation { get; set; }

    public virtual ICollection<NotificationChat> NotificationChats { get; set; } = new List<NotificationChat>();

    public virtual ICollection<NotificationEvent> NotificationEvents { get; set; } = new List<NotificationEvent>();

    public virtual ICollection<NotificationTask> NotificationTasks { get; set; } = new List<NotificationTask>();

    public virtual ICollection<NotificationVitalSignDetail> NotificationVitalSignDetails { get; set; } = new List<NotificationVitalSignDetail>();

    public virtual Type notificationTypeCodeNavigation { get; set; }

    public virtual User user { get; set; }
}