// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class NotificationMessageTemplate
{
    public int id { get; set; }

    public string notificationgroupCode { get; set; }

    public string notificationSubject { get; set; }

    public string notificationMessage { get; set; }

    public DateTime createdDate { get; set; }

    public DateTime? updatedDate { get; set; }

    public virtual Type notificationgroupCodeNavigation { get; set; }
}