// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class NotificationChat
{
    public int NotificationChatID { get; set; }

    public int NotificationId_FK { get; set; }

    public int ChatID_FK { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public virtual Chat ChatID_FKNavigation { get; set; }

    public virtual Notification NotificationId_FKNavigation { get; set; }
}