// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class NutritionTaskReference
{
    public int ReferenceID { get; set; }

    public int CodeId_FK { get; set; }

    public string ReferenceImage { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedBy_FK { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy_FK { get; set; }

    public bool IsDeleted { get; set; }

    public int? Value { get; set; }

    public virtual Code CodeId_FKNavigation { get; set; }

    public virtual ICollection<NutritionTask> NutritionTaskAmountReferenceID_FKNavigations { get; set; } = new List<NutritionTask>();

    public virtual ICollection<NutritionTask> NutritionTaskColorReferenceID_FKNavigations { get; set; } = new List<NutritionTask>();

    public virtual ICollection<NutritionTask> NutritionTaskTypeReferenceID_FKNavigations { get; set; } = new List<NutritionTask>();
}