// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class Otp
{
    public int OtpId { get; set; }

    public int UserId { get; set; }

    public string Password { get; set; }

    public DateTime CreatedDate { get; set; }
}