// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class PatientBradenScale
{
    public int PatientBradenScaleID { get; set; }

    public string Type { get; set; }

    public int? VitalSignDetailID_FK { get; set; }

    public int? Score1 { get; set; }

    public int? Score2 { get; set; }

    public int? Score3 { get; set; }

    public int? Score4 { get; set; }

    public int? Score5 { get; set; }

    public int? Score6 { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedBy_FK { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy_FK { get; set; }

    public bool IsDeleted { get; set; }

    public virtual VitalSignDetail VitalSignDetailID_FKNavigation { get; set; }
}