// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class PatientMedicationConsumeAttachment
{
    public int PatientMedicationConsumeAttachmentID { get; set; }

    public int PatientMedicationConsumeID_FK { get; set; }

    public string Filename { get; set; }

    public string Physical { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedBy_FK { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy_FK { get; set; }

    public bool IsDeleted { get; set; }

    public bool? IsEndDate { get; set; }

    public virtual PatientMedicationConsume PatientMedicationConsumeID_FKNavigation { get; set; }
}