// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class Patient
{
    public int PatientID { get; set; }

    public string Firstname { get; set; }

    public string Lastname { get; set; }

    public string NRIC { get; set; }

    public DateTime? DateOfBirth { get; set; }

    public int? Age { get; set; }

    public string PostalCode { get; set; }

    public string Photo { get; set; }

    public int? CareManagerAssignedID { get; set; }

    public string CaseID { get; set; }

    public string DrugAllergy { get; set; }

    public string Status { get; set; }

    public int? DischargeNoticePeriodInMonths { get; set; }

    public DateTime? AdmittedDate { get; set; }

    public string ReasonOfAdmission { get; set; }

    public bool? AMD { get; set; }

    public bool? ACP { get; set; }

    public bool? PACEMAKER { get; set; }

    public bool? ACID { get; set; }

    public string MobilePhone { get; set; }

    public string HomePhone { get; set; }

    public string Email { get; set; }

    public string GenogramPicture { get; set; }

    public string ReferringDiagnosis { get; set; }

    public string MailForVitalAlert1 { get; set; }

    public string MailForVitalAlert2 { get; set; }

    public string MailForVitalAlert3 { get; set; }

    public string MailForFamilyNotification1 { get; set; }

    public string MailForFamilyNotification2 { get; set; }

    public string VisitingFrequency { get; set; }

    public int? NumberOfChildren { get; set; }

    public string Occupation { get; set; }

    public bool? UpfrontPayment { get; set; }

    public DateTime? CareReviewDate { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedBy_FK { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy_FK { get; set; }

    public int? PatientTypeID_FK { get; set; }

    public string MailingAddress1 { get; set; }

    public string MailingAddress2 { get; set; }

    public string MailingAddress3 { get; set; }

    public int? GenderID_FK { get; set; }

    public int? BloodTypeID_FK { get; set; }

    public int? ResidentTypeID_FK { get; set; }

    public int? MaritalStatusID_FK { get; set; }

    public int? ReligionID_FK { get; set; }

    public int? PatientProfileID_FK { get; set; }

    public int? RaceID_FK { get; set; }

    public int? PatientAdditionalInfoID_FK { get; set; }

    public int? PatientReferralID_FK { get; set; }

    public string MedicalHistoryRemarks { get; set; }

    public int? PatientMedicationID_FK { get; set; }

    public int? PatientReferralByID_FK { get; set; }

    public string IdentificationNumber { get; set; }

    public string IdentificationAttachmentFilename { get; set; }

    public string IdentificationAttachmentPhysical { get; set; }

    public string OtherRace { get; set; }

    public string OtherLanguage { get; set; }

    public string PaymentMode { get; set; }

    public int? InvoiceModeID_FK { get; set; }

    public string DisplayName { get; set; }

    public string OrderID { get; set; }

    public bool? Accepted { get; set; }

    public string NursingStation { get; set; }

    public int? AccessHospitalID_FK { get; set; }

    public string ActionDescription { get; set; }

    public string IntegrationSourceID { get; set; }

    public virtual ICollection<BillingInvoice> BillingInvoices { get; set; } = new List<BillingInvoice>();

    public virtual ICollection<BillingProposal> BillingProposals { get; set; } = new List<BillingProposal>();

    public virtual Code BloodTypeID_FKNavigation { get; set; }

    public virtual ICollection<CarePlan> CarePlans { get; set; } = new List<CarePlan>();

    public virtual ICollection<CareReport> CareReports { get; set; } = new List<CareReport>();

    public virtual ICollection<Chat> Chats { get; set; } = new List<Chat>();

    public virtual Code GenderID_FKNavigation { get; set; }

    public virtual Code InvoiceModeID_FKNavigation { get; set; }

    public virtual Code MaritalStatusID_FKNavigation { get; set; }

    public virtual ICollection<MultiDisciplinaryMeeting> MultiDisciplinaryMeetings { get; set; } = new List<MultiDisciplinaryMeeting>();

    public virtual ICollection<NutritionTask> NutritionTasks { get; set; } = new List<NutritionTask>();

    public virtual ICollection<PatientAMT> PatientAMTs { get; set; } = new List<PatientAMT>();

    public virtual PatientAdditionalInfo PatientAdditionalInfoID_FKNavigation { get; set; }

    public virtual ICollection<PatientAttachment> PatientAttachments { get; set; } = new List<PatientAttachment>();

    public virtual ICollection<PatientClinician> PatientClinicians { get; set; } = new List<PatientClinician>();

    public virtual ICollection<PatientDrugAllergy> PatientDrugAllergies { get; set; } = new List<PatientDrugAllergy>();

    public virtual ICollection<PatientEBASDEP> PatientEBASDEPs { get; set; } = new List<PatientEBASDEP>();

    public virtual ICollection<PatientFamilyHistory> PatientFamilyHistories { get; set; } = new List<PatientFamilyHistory>();

    public virtual ICollection<PatientImmunisation> PatientImmunisations { get; set; } = new List<PatientImmunisation>();

    public virtual ICollection<PatientMedicalHistory> PatientMedicalHistories { get; set; } = new List<PatientMedicalHistory>();

    public virtual PatientMedication PatientMedicationID_FKNavigation { get; set; }

    public virtual ICollection<PatientOtherAllergy> PatientOtherAllergies { get; set; } = new List<PatientOtherAllergy>();

    public virtual PatientProfile PatientProfileID_FKNavigation { get; set; }

    public virtual Code PatientReferralByID_FKNavigation { get; set; }

    public virtual PatientReferral PatientReferralID_FKNavigation { get; set; }

    public virtual ICollection<PatientSocialSupport> PatientSocialSupports { get; set; } = new List<PatientSocialSupport>();

    public virtual Code PatientTypeID_FKNavigation { get; set; }

    public virtual ICollection<PatientWoundDraft> PatientWoundDrafts { get; set; } = new List<PatientWoundDraft>();

    public virtual ICollection<PatientWound> PatientWounds { get; set; } = new List<PatientWound>();

    public virtual Code RaceID_FKNavigation { get; set; }

    public virtual ICollection<Receipt> Receipts { get; set; } = new List<Receipt>();

    public virtual ICollection<RecentView> RecentViews { get; set; } = new List<RecentView>();

    public virtual Code ReligionID_FKNavigation { get; set; }

    public virtual Code ResidentTypeID_FKNavigation { get; set; }

    public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();

    public virtual ICollection<TeleconsultationRecording> TeleconsultationRecordings { get; set; } = new List<TeleconsultationRecording>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();

    public virtual ICollection<VitalSignRelationship> VitalSignRelationships { get; set; } = new List<VitalSignRelationship>();

    public virtual ICollection<VitalSign> VitalSigns { get; set; } = new List<VitalSign>();

    public virtual ICollection<Code> CodeID_FKs { get; set; } = new List<Code>();

    public virtual ICollection<Code> CodeID_FKsNavigation { get; set; } = new List<Code>();

    public virtual ICollection<Facility> FacilityID_FKs { get; set; } = new List<Facility>();

    public virtual ICollection<Package> PackageID_FKs { get; set; } = new List<Package>();
}