// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class PatientEBASDEP
{
    public int PatientEBASDEPID { get; set; }

    public int? PatientID_FK { get; set; }

    public int? InitialCareAssessmentID_FK { get; set; }

    public string Alertness { get; set; }

    public int? Score { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedBy_FK { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy_FK { get; set; }

    public bool IsDeleted { get; set; }

    public int? CareReportID_FK { get; set; }

    public int? VitalSignDetailId_FK { get; set; }

    public virtual CareReport CareReportID_FKNavigation { get; set; }

    public virtual InitialCareAssessment InitialCareAssessmentID_FKNavigation { get; set; }

    public virtual ICollection<PatientEBASDEPAnswer> PatientEBASDEPAnswers { get; set; } = new List<PatientEBASDEPAnswer>();

    public virtual Patient PatientID_FKNavigation { get; set; }

    public virtual VitalSignDetail VitalSignDetailId_FKNavigation { get; set; }
}