// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class PatientWoundDraftTreatmentList
{
    public int PatientWoundDraftTListID { get; set; }

    public int PatientWoundDraftID_FK { get; set; }

    public int TListItemID_FK { get; set; }

    public string Remarks { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedBy_FK { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy_FK { get; set; }

    public virtual PatientWoundDraft PatientWoundDraftID_FKNavigation { get; set; }

    public virtual TreatmentListItem TListItemID_FKNavigation { get; set; }
}