// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class PatientMedication
{
    public int PatientMedicationID { get; set; }

    public string Allergies { get; set; }

    public bool? SelfAdminister { get; set; }

    public bool? Compliant { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedBy_FK { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy_FK { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<InitialCareAssessment> InitialCareAssessments { get; set; } = new List<InitialCareAssessment>();

    public virtual ICollection<PatientMedicationConsume> PatientMedicationConsumes { get; set; } = new List<PatientMedicationConsume>();

    public virtual ICollection<Patient> Patients { get; set; } = new List<Patient>();

    public virtual ICollection<Code> SupplyID_FKs { get; set; } = new List<Code>();
}