// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class ReceiptForInvoice
{
    public int ReceiptForInvoiceID { get; set; }

    public int ReceiptID_FK { get; set; }

    public int BillingInvoiceID_FK { get; set; }

    public decimal Amt { get; set; }

    public virtual BillingInvoice BillingInvoiceID_FKNavigation { get; set; }

    public virtual Receipt ReceiptID_FKNavigation { get; set; }
}