// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class Role
{
    public int RoleId { get; set; }

    public string RoleDescription { get; set; }

    public string OptionText { get; set; }

    public string OptionValue { get; set; }

    public string OptionType { get; set; }

    public int Ordering { get; set; }

    public DateTime DateCreated { get; set; }

    public bool? Active { get; set; }

    public virtual ICollection<GroupRole> GroupRoles { get; set; } = new List<GroupRole>();

    public virtual ICollection<UserCategoryRole> UserCategoryRoles { get; set; } = new List<UserCategoryRole>();

    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
}