// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class ScheduledTask
{
    public int ScheduleId { get; set; }

    public string ScheduleDescription { get; set; }

    public string PerformTask { get; set; }

    public bool Everyday { get; set; }

    public bool Weekday { get; set; }

    public int NDays { get; set; }

    public string WeekDays { get; set; }

    public DateTime? TimeStart { get; set; }

    public DateTime? TimeEnd { get; set; }

    public int Interval { get; set; }

    public string IntervalType { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? NextRun { get; set; }

    public DateTime? LastRun { get; set; }

    public string Status { get; set; }
}