// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class TeleconsultationReport
{
    public int TeleReportID { get; set; }

    public int MediaType { get; set; }

    public int TaskID_FK { get; set; }

    public int PatientID_FK { get; set; }

    public string Memo { get; set; }

    public string Status { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? CreatedBy_FK { get; set; }

    public int? ModifiedBy_FK { get; set; }

    public DateOnly? ModifiedDate { get; set; }
}