// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class TeleconsultationRecording
{
    public int RecordingID { get; set; }

    public int RecordingType_FK { get; set; }

    public int PatientID_FK { get; set; }

    public string Sid { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? CreatedBy_FK { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy_FK { get; set; }

    public virtual Patient PatientID_FKNavigation { get; set; }

    public virtual Code RecordingType_FKNavigation { get; set; }
}