// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class UserCategory
{
    public int UserCategoryID { get; set; }

    public string UserCategory1 { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedBy_FK { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy_FK { get; set; }

    public bool IsDeleted { get; set; }

    public int? UserCategoryOrganizationID_FK { get; set; }

    public bool? EnableGeoFencing { get; set; }

    public virtual ICollection<Event> Events { get; set; } = new List<Event>();

    public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();

    public virtual Code UserCategoryOrganizationID_FKNavigation { get; set; }

    public virtual ICollection<UserCategoryRole> UserCategoryRoles { get; set; } = new List<UserCategoryRole>();

    public virtual ICollection<UserType> UserTypes { get; set; } = new List<UserType>();

    public virtual ICollection<UserCategory> ChildUserCategoryID_FKs { get; set; } = new List<UserCategory>();

    public virtual ICollection<Facility> FacilityID_FKs { get; set; } = new List<Facility>();

    public virtual ICollection<UserCategory> ParentUserCategoryID_FKs { get; set; } = new List<UserCategory>();
}