// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class UserCategoryRole
{
    public int UserCategoryID_FK { get; set; }

    public int RoleID_FK { get; set; }

    public string Role { get; set; }

    public virtual Role RoleID_FKNavigation { get; set; }

    public virtual UserCategory UserCategoryID_FKNavigation { get; set; }
}