// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class UserRole
{
    public int UserId_FK { get; set; }

    public int RoleId_FK { get; set; }

    public string Role { get; set; }

    public virtual Role RoleId_FKNavigation { get; set; }

    public virtual User UserId_FKNavigation { get; set; }
}