// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class User
{
    public int UserId { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Firstname { get; set; }

    public string Lastname { get; set; }

    public string Remarks { get; set; }

    public string Photo { get; set; }

    public string Contact { get; set; }

    public string Designation { get; set; }

    public string Status { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? CreatedBy_FK { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy_FK { get; set; }

    public DateTime? LastLoginDate { get; set; }

    public DateTime? LastLogoutDate { get; set; }

    public DateTime? LastActivityDate { get; set; }

    public DateTime? LastLockoutDate { get; set; }

    public DateTime? LastPasswordChangedDate { get; set; }

    public string PreviousPasswords { get; set; }

    public string SessionKey { get; set; }

    public bool? ResetPassword { get; set; }

    public bool IsDeleted { get; set; }

    public string LocationNow1 { get; set; }

    public string LocationNow2 { get; set; }

    public string LocationNow3 { get; set; }

    public string PostalCodeNow { get; set; }

    public DateTime? LocationNowModifiedDate { get; set; }

    public int? PatientID_FK { get; set; }

    public bool IsExternal { get; set; }

    public int? UserOrganizationID_FK { get; set; }

    public bool? IsTCAccepted { get; set; }

    public string UserName { get; set; }

    public int? PreferredLanguage { get; set; }

    public int? AccessLevelID_FK { get; set; }

    public bool HasValidEmail { get; set; }

    public string TokenID { get; set; }

    public string PreviousPasswords2 { get; set; }

    public bool? SharePdf { get; set; }

    public virtual ICollection<AuditTrail> AuditTrails { get; set; } = new List<AuditTrail>();

    public virtual ICollection<BillingInvoice> BillingInvoiceCreatedBy_FKNavigations { get; set; } = new List<BillingInvoice>();

    public virtual ICollection<BillingInvoice> BillingInvoiceModifiedBy_FKNavigations { get; set; } = new List<BillingInvoice>();

    public virtual ICollection<BillingProposal> BillingProposalCreatedBy_FKNavigations { get; set; } = new List<BillingProposal>();

    public virtual ICollection<BillingProposal> BillingProposalModifiedBy_FKNavigations { get; set; } = new List<BillingProposal>();

    public virtual ICollection<CareReportSystemInfo> CareReportSystemInfoKeyPerson1UserID_FKNavigations { get; set; } = new List<CareReportSystemInfo>();

    public virtual ICollection<CareReportSystemInfo> CareReportSystemInfoKeyPerson2UserID_FKNavigations { get; set; } = new List<CareReportSystemInfo>();

    public virtual ICollection<CareReport> CareReports { get; set; } = new List<CareReport>();

    public virtual ICollection<Chat> Chats { get; set; } = new List<Chat>();

    public virtual ICollection<Enquiry> Enquiries { get; set; } = new List<Enquiry>();

    public virtual ICollection<EnquiryConfig> EnquiryConfigEscalatingPersonID_FKNavigations { get; set; } = new List<EnquiryConfig>();

    public virtual ICollection<EnquiryConfig> EnquiryConfigSCMID_FKNavigations { get; set; } = new List<EnquiryConfig>();

    public virtual ICollection<EventUserLog> EventUserLogs { get; set; } = new List<EventUserLog>();

    public virtual ICollection<EventUser> EventUsers { get; set; } = new List<EventUser>();

    public virtual ICollection<Event> Events { get; set; } = new List<Event>();

    public virtual ICollection<MobileAppVersioning> MobileAppVersioningCreatedBy_FKNavigations { get; set; } = new List<MobileAppVersioning>();

    public virtual ICollection<MobileAppVersioning> MobileAppVersioningModifiedBy_FKNavigations { get; set; } = new List<MobileAppVersioning>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<PatientClinician> PatientClinicians { get; set; } = new List<PatientClinician>();

    public virtual Patient PatientID_FKNavigation { get; set; }

    public virtual ICollection<PatientWoundReviewBy> PatientWoundReviewBies { get; set; } = new List<PatientWoundReviewBy>();

    public virtual ICollection<PatientWoundVisitClinician> PatientWoundVisitClinicians { get; set; } = new List<PatientWoundVisitClinician>();

    public virtual ICollection<PatientWoundVisit> PatientWoundVisits { get; set; } = new List<PatientWoundVisit>();

    public virtual ICollection<Receipt> ReceiptCreatedBy_FKNavigations { get; set; } = new List<Receipt>();

    public virtual ICollection<Receipt> ReceiptModifiedBy_FKNavigations { get; set; } = new List<Receipt>();

    public virtual ICollection<RecentView> RecentViews { get; set; } = new List<RecentView>();

    public virtual ICollection<TaskUserLog> TaskUserLogs { get; set; } = new List<TaskUserLog>();

    public virtual ICollection<TaskUser> TaskUsers { get; set; } = new List<TaskUser>();

    public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();

    public virtual ICollection<UserAddress> UserAddresses { get; set; } = new List<UserAddress>();

    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();

    public virtual ICollection<Branch> BranchID_FKs { get; set; } = new List<Branch>();

    public virtual ICollection<Code> CodeID_FKs { get; set; } = new List<Code>();

    public virtual ICollection<Code> CodeID_FKsNavigation { get; set; } = new List<Code>();

    public virtual ICollection<EnquiryConfig> EnquiryConfigID_FKs { get; set; } = new List<EnquiryConfig>();

    public virtual ICollection<EnquiryConfig> EnquiryConfigs { get; set; } = new List<EnquiryConfig>();

    public virtual ICollection<Code> LanguageID_FKs { get; set; } = new List<Code>();

    public virtual ICollection<UserType> UserTypeID_FKs { get; set; } = new List<UserType>();
}