// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class UUIDLog
{
    public int UUIDLogID { get; set; }

    public string UUID { get; set; }

    public bool? IsUpdated { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedBy_FK { get; set; }

    public int? PatientWoundVisitID { get; set; }
}