// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class VitalSignDetail
{
    public int id { get; set; }

    public int vitalSignTypeId { get; set; }

    public int vitalSignId { get; set; }

    public decimal detailValue { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<NotificationVitalSignDetail> NotificationVitalSignDetails { get; set; } = new List<NotificationVitalSignDetail>();

    public virtual ICollection<PatientAMT> PatientAMTs { get; set; } = new List<PatientAMT>();

    public virtual ICollection<PatientBradenScale> PatientBradenScales { get; set; } = new List<PatientBradenScale>();

    public virtual ICollection<PatientEBASDEP> PatientEBASDEPs { get; set; } = new List<PatientEBASDEP>();

    public virtual ICollection<PatientGC> PatientGCs { get; set; } = new List<PatientGC>();

    public virtual ICollection<PatientMBI> PatientMBIs { get; set; } = new List<PatientMBI>();

    public virtual ICollection<PatientMF> PatientMFs { get; set; } = new List<PatientMF>();

    public virtual ICollection<PatientMMSE> PatientMMSEs { get; set; } = new List<PatientMMSE>();

    public virtual ICollection<PatientRAF> PatientRAFs { get; set; } = new List<PatientRAF>();

    public virtual VitalSign vitalSign { get; set; }

    public virtual VitalSignType vitalSignType { get; set; }
}