// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class VitalSignRelationship
{
    public int id { get; set; }

    public int vitalSignTypeId { get; set; }

    public int patientId { get; set; }

    public int thresholdId { get; set; }

    public virtual Patient patient { get; set; }

    public virtual Threshold threshold { get; set; }

    public virtual VitalSignType vitalSignType { get; set; }
}