// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class vw_CarePlanSystemDisease
{
    public int CarePlanID { get; set; }

    public int SystemID_FK { get; set; }

    public int DiseaseID_FK { get; set; }

    public bool? IsDeleted { get; set; }

    public bool? IsClosed { get; set; }
}