// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class vw_Doctor
{
    public int? InternalId { get; set; }

    public int? ExternalId { get; set; }

    public string DoctorName { get; set; }
}