// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class vw_FalangaScores_WoundDraft
{
    public int PatientWoundDraftID { get; set; }

    public string HealingEdges { get; set; }

    public int HealingEdges_Score { get; set; }

    public string BlackEschar { get; set; }

    public int BlackEschar_Score { get; set; }

    public string GreatestWoundDepth { get; set; }

    public int GreatestWoundDepth_Score { get; set; }

    public string ExudateAmount { get; set; }

    public int ExudateAmount_Score { get; set; }

    public bool? Edema { get; set; }

    public int Edema_Score { get; set; }

    public string PeriwoundDermatitis { get; set; }

    public int PeriwoundDermatitis_Score { get; set; }

    public string PeriwoundCallousFibrosis { get; set; }

    public int PeriwoundCallousFibrosis_Score { get; set; }

    public string PinkWoundBed { get; set; }

    public int PinkWoundBed_Score { get; set; }

    public int? TotalScore { get; set; }
}