// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class vw_PushScore
{
    public int PatientWoundVisitID { get; set; }

    public int LengthXWidthScore { get; set; }

    public int ExudateAmountScore { get; set; }

    public int TissueTypeScore { get; set; }

    public int? TotalScore { get; set; }
}