// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class vw_PatientBilling
{
    public int? PatientProfileID_FK { get; set; }

    public string PatientName { get; set; }

    public string Email { get; set; }

    public string BillingAddress1 { get; set; }

    public string BillingAddress2 { get; set; }

    public string BillingAddress3 { get; set; }

    public string BillingPostalCode { get; set; }
}