// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace C4WX1_DbMigrator.Models;

public partial class WoundUserCategoryParentChild
{
    public int ParentUserCategoryID_FK { get; set; }

    public int ChildUserCategoryID_FK { get; set; }
}